### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by Lifeischoice** [VibeThemes/wplms_vc_templates#1]
Please check the description in the this header ...is this correct?

Plugin Name: WPLMS VC Templates
Plugin URI: http://www.Vibethemes.com
Description: A WPLMS Addon to calculate the time spent by users inside the course.
Version: 1.1
Author: Vibethemes

**Comment by MrVibe** [comment]
no, thanks for pointing out. Marked as bug.

**Comment by MrVibe** [comment]
resolved. https://github.com/VibeThemes/wplms_vc_templates/commit/01ed57c5707ef702846911a6ad3bf04832564a3b
